### ISSUE TITLE
Replace [reply] with more organic irc-style reply

### ISSUE THREAD

**Issue by qaisjp** [qaisjp/go-discord-irc#100]
It should say

PersonRepliedToUsername: MESSAGE

instead of 

[reply] MESSAGE

**Comment by llmII** [comment]
See #86 as well, will definitely want to integrate formatting for it (if go-discord-irc will be supporting formatting). Also points at something relevant for pulling down the old message and an idea for truncation. Think being able to include (possibly truncated) the replied to message in the reply would be helpful when the person being replied to is actively conversating on multiple subjects or the reply distance is large.

**Comment by qaisjp** [comment]
Feel free to add it if you really need it, however maybe we can just make the bot be configured to do the best thing, and add configuration support only where it really needs it.

E.g. maybe we could include truncated context if there's a reply distance of `n` minutes (real easy to determine based on snowflake), and maybe in the future > `n` messages (not a fun data model!)
