### ISSUE TITLE
Capital letters in channel name problem

### ISSUE THREAD

**Issue by h1x0r1** [qaisjp/go-discord-irc#115]
I have channels with first capital letter in the name. Like #Test . When i add it in config all puppets join in the channel when i write from discord to irc everything is like a charm. But the problem is in other side when i try to send message from irc to discord ... Houston, we have a problem.... messages not send it to discord channel and in debug we have "WARN[0028] Ignoring message sent from an unhandled IRC channel." 
My conf raw is : 
"#Test": Discord Channel iD
the Irc channel is #Test again with the capital first letter.
When i have many users to that channel i need to ban everyone to change the name of the channel with only small letters. 
Please help to solve this problem.

**Comment by Rapman4** [comment]
Hi
I have resolved the problem in the bridge.go file line 372

mapping, ok := b.GetMappingByIRC(strings.ToLower(msg.IRCChannel))

**Comment by qaisjp** [comment]
I applied a variant of Rapman4's fix. Please try the latest master and tell me if it fixes the problem

**Comment by h1x0r1** [comment]
> I applied a variant of Rapman4's fix. Please try the latest master and tell me if it fixes the problem

With the channel problem now everything is fine.  Good job!

**Comment by qaisjp** [comment]
thanks! credits to rapman4
