### ISSUE TITLE
time="2022-10-16T01:40:24Z" level=fatal msg="Go-Discord-IRC failed to start." error="can't open irc connection: x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0"

### ISSUE THREAD

**Issue by radmx** [qaisjp/go-discord-irc#140]
any idea?

**Comment by cardonator** [comment]
The message implies that the certificate installed on the IRC server isn't correctly formed. Is it a public irc server? I got something similar and just disabled tls.

**Comment by qaisjp** [comment]
thanks for suggesting that workaround @cardonator!

going to close this one as wontfix, i'm happy to revisit if it's a massive pain for lots of people but it sounds like there's a known workaround here
