### ISSUE TITLE
tls: oversized record received with length 20306

### ISSUE THREAD

**Issue by syrm** [qaisjp/go-discord-irc#19]
Hello,

I got this error : 
`ERRO[0005] error opening irc connection                  error="tls: oversized record received with length 20306"` after 10 connections of users.

**Comment by qaisjp** [comment]
Hi, this will most likely be the IRC server rejecting further connections.

**Comment by qaisjp** [comment]
Closing because stale. happy to reopen this with further information. If you have figured out a (local) solution I'm happy to merge it

**Comment by mediamagnet** [comment]
@qaisjp I've ran into the same issue myself I've disabled the webirc setting as i'm connecting to freenode and doubt i could get that from them  I also have tls set to false. unlike syrm I'm not able to establish a connection to freenode or my local inspircd server. 

I'm running go version go1.11.2 linux/amd64

**Comment by qaisjp** [comment]
@mediamagnet is this after 10 connections or are you not able to do any connections?

**Comment by mediamagnet** [comment]
not able to do any.

**Comment by qaisjp** [comment]
weird. what happens if you connec to your local inspircd server without tls?

**Comment by mediamagnet** [comment]
```FATA[0000] Go-Discord-IRC failed to start.               error="can't open irc connection: tls: oversized record received with length 24948"
exit status 1``` and this is with setting insecure to true in my config

**Comment by qaisjp** [comment]
`insecure` only skips TLS _verification_, it does not _disable_ TLS.

to disable tls you need to comment out these lines https://github.com/qaisjp/go-discord-irc/blob/f00ac4b/bridge/bridge.go#L267-L270

**Comment by qaisjp** [comment]
same error? you should not get a tls error if there's no tls

**Comment by mediamagnet** [comment]
this is what i'm getting on launch:

`$ go run main.go --config test.yaml --debug
INFO[0000] Loading configuration...                      ConfigName=test ConfigPath=. ConfigType=yaml
WARN[0000] webirc_pass is empty
FATA[0001] Go-Discord-IRC failed to start.               error="can't open irc connection: tls: oversized record received with length 24948"
exit status 1`
