### ISSUE TITLE
Add Dockerfile and Docker Hub image

### ISSUE THREAD

**Issue by ismell** [qaisjp/go-discord-irc#34]
It would be nice if there was a Dockerfile so the app could be easily deployed. Additionally setting up Docker Hub to consume the Docker file would be a plus.

**Comment by qaisjp** [comment]
I suppose, yes. I am happy to accept pull requests for this.

I am hesitant to add new features as I prefer @42wim's [matterbridge](https://github.com/42wim/matterbridge). I really need to get round to adding the puppet feature there!

**Comment by poVoq** [comment]
> I prefer @42wim's matterbridge. I really need to get round to adding the puppet feature there!

That would be really appreciated!

**Comment by poVoq** [comment]
Dockerhub image also planned?

**Comment by qaisjp** [comment]
i've created a thing here https://hub.docker.com/r/qaisjp/go-discord-irc

i've triggered a build when creating the repo ("Build & Create"), no idea how long it will take.

i'm getting on a flight soon, and will see how it looks in ~12 hours

**Comment by poVoq** [comment]
Yeah, normally takes a good while. Thanks a lot!
