### ISSUE TITLE
Add support for non-ssl IRC servers

### ISSUE THREAD

**Issue by pbsds** [qaisjp/go-discord-irc#36]
Our irc network doesn't have any SSL/TLS support. We'd still like to bridge it with our discord server though. I thought `insecure: true` would solve our problems, but due to the hardcoded line [here](https://github.com/qaisjp/go-discord-irc/blob/master/bridge/bridge.go#L267) it sadly does not.

We're getting the error:

    time="2019-09-21T15:37:32Z" level=fatal msg="Go-Discord-IRC failed to start." error="can't open irc connection: tls: first record does not look like a TLS handshake"

Could support for non-ssl connections be added? Preferably with a stern warning against it?

**Comment by qaisjp** [comment]
I'm happy to accept pull requests that modifies this bridge to accept a `--no-tls` command line argument
