### ISSUE TITLE
Just use one webhook

### ISSUE THREAD

**Issue by qaisjp** [qaisjp/go-discord-irc#40]
This will make it closer in behaviour to matterbridge. Also, occasionally webhooks get out of sync and end up writing to the wrong channel

**Comment by bluddy** [comment]
Does this mean that the readme is incorrect and we no longer need to give the bot permission to create webhooks? Why were multiple webhooks used to begin with, if I may inquire?

**Comment by qaisjp** [comment]
The WebhookCreate permission is still needed as it automatically creates a single webhook when necessary, and there's no way to specify a specific webhook to use. (It will also clean up the automatically created webhook when the bot is stopped / started.)

Multiple webhooks were required due a Discord Android bug where messages from the same webhook (even with a different username set) would be collapsed together into one message. So we needed multiple webhooks so that two adjacent users never used the same webhook.

This is what it used to look like (Android only) [0]:

![image](https://user-images.githubusercontent.com/923242/87853207-2bc90a00-c900-11ea-8be4-525166ac6c98.png)

This is what the same messages look like today (on all platforms):

![image](https://user-images.githubusercontent.com/923242/87853153-d3920800-c8ff-11ea-8a13-8c93513a98c7.png)


It also took into account that, on Discord + all platforms, messages from different webhooks would _not_ collapse together, even if they had the same name. So it would do a bit of magic to create extra webhooks so that conversations happening in multiple channels simultaneously would have their own webhooks, while also not creating too many webhooks. Because we only use one webhook today, we don't need to worry about this edge case.

[0] [discord link to CompSoc server](https://discordapp.com/channels/315277951597936640/315277951597936640/347805486210351105) from when I shared this screenshot

**Comment by bluddy** [comment]
Well, given the fact that only one webhook is used, wouldn't it make sense to just tell it which one? I imagine this would be a step needed to integrate into matterbridge as well, and reducing permissions is always good.

**Comment by qaisjp** [comment]
Yes. Although I find it incredibly convenient to have the creation of webhooks work live. It makes setup a little easier + makes it more flexible as If, for some reason, messages get sent to the wrong channel, a quick fix is to just delete the webhook and let the bot recreate it automatically. (I've also had this auto-creation feature on my matterbridge to-do list.)

**Comment by bluddy** [comment]
On the other hand, the nice thing about webhooks being deterministic is that it's easy for the discord admins to control things without touching the bot. Being bound to a webhook means that the admins can redirect the bot to another channel if need be. For example, I'm currently running the matterbridge bot on a dedicated #irc channel, but I'm considering moving it to #general, and that's trivial to do from discord. Actually, I'm not currently planning on doing that, and the only way I'd move it to the main channel is if I change the bot to be this one, so the experience is rich enough on both sides that neither one is hurt once they're fully connected.

**Comment by qaisjp** [comment]
Hmm, that's an interesting use-case but then we'd have an interesting mix of config managed by config file AND discord webhook settings.

I'm not aware of any bridges that are flexible enough this way — they usually have a config setting to at least determine which Discord channel should have their messages routed to IRC — that's not to say we can't do it, but I'm just not sure it's worth the effort.

One way would to replace the Discord channel ID in the config with a webhook URL, and to have channel ID be updated and tracked internally (during runtime).
