### ISSUE TITLE
Extremely long Discord names cause echo

### ISSUE THREAD

**Issue by Kirtaner** [qaisjp/go-discord-irc#42]
When a user on Discord has a name that is longer than the supported NICKLEN/MAXNICKLEN of the IRCd, their name is truncated and the bridge gets confused when they speak due to the configured prefix not being present, causing all of their messages to be echoed.

Either a config setting or detection of MAXNICKLEN on connect (or both) would take care of this. Truncate the name accordingly or fallback to their Discord username.

**Comment by qaisjp** [comment]
Hmm. I thought I accounted for this. Either my code is long, or [the nicklen I have hardcoded](https://github.com/qaisjp/go-discord-irc/blob/master/irc/nick/consts.go#L35) does not match the IRCd's.

Is there a standard way to get the max nick length? `MAXNICKLEN` is mentioned on [this page](http://www.irc.org/tech_docs/005.html) (which was last updated in  2004) 

Config is a reasonable short-term solution.

**Comment by ThiefMaster** [comment]
the 005 numeric is the way to go to get such information from the ircd

**Comment by Phosphorus-M** [comment]
Same problem, I changed the ```MAXNICKLEN``` but the problem continue

**Comment by llmII** [comment]
Could someone check if #69 fixed this? If not I might work on an Even Better Puppet Detection feature sometime soonish.

**Comment by qaisjp** [comment]
this probably fixed it since it's no longer detected by suffix. thanks!
