### ISSUE TITLE
Sporadic missing nick suffixes causing echoes

### ISSUE THREAD

**Issue by Kirtaner** [qaisjp/go-discord-irc#43]
On our server, sometimes user's IRC puppets are connected without the configured suffix and all of their chat is echoed.

**Comment by qaisjp** [comment]
What do you mean by "`all of their chat is echoed`"?

**Comment by Kirtaner** [comment]
This is also happening with MEE6 (and possibly other bots) when it has a custom name

**Comment by qaisjp** [comment]
Yeah that's weird
