### ISSUE TITLE
Puppets permanently connected after user leaves Discord server

### ISSUE THREAD

**Issue by Kirtaner** [qaisjp/go-discord-irc#45]
Currently only restarting the bridge will remove IRC connections that are no longer valid.

However, this might be better as a configurable setting as large Discord servers would subject the IRC channels with elevated amounts of join/part spam.

**Comment by qaisjp** [comment]
Yeah, we can probably just make them quit with reason "Left Discord server". With a setting to instead just translate that into a "going offline" message, so it will quit after the defined number of hours

**Comment by bluddy** [comment]
Seems like a pretty serious bug. Any intention of fixing this?

(I'm considering moving from matterbridge to this far superior implementation, at least until matterbridge catches up)

**Comment by qaisjp** [comment]
Yes, it's a pretty easy fix, I just need to get round to doing it! Let me see...

**Comment by qaisjp** [comment]
Alright, now the irc connection immediately leaves the server when the Discord user does.

This doesn't include the suggestion of reducing join/quit spam. If someone wants it, I can add it.
