### ISSUE TITLE
webhook.go:33:2: too many arguments to return

### ISSUE THREAD

**Issue by Lucki** [qaisjp/go-discord-irc#46]
When running `go get github.com/qaisjp/go-discord-irc` I get the following error message:

~~~
# github.com/qaisjp/go-discord-irc/transmitter
go/src/github.com/qaisjp/go-discord-irc/transmitter/webhook.go:33:2: too many arguments to return
	have (*discordgo.Message, error)
	want (error)
~~~

**Comment by qaisjp** [comment]
Please can you try `go get -u github.com/qaisjp/go-discord-irc`?

**Comment by Lucki** [comment]
`go get -u github.com/qaisjp/go-discord-irc` results in the same error message.

**Comment by qaisjp** [comment]
OK, it should be fixed now!

**Comment by qaisjp** [comment]
OK, it should be fixed now! Thanks for reporting this :)

**Comment by Lucki** [comment]
Confirmed working, thanks!
