### ISSUE TITLE
PRIVMSG being sent in response to NOTICE causing message loop

### ISSUE THREAD

**Issue by ja5087** [qaisjp/go-discord-irc#50]
It seems that NOTICE messages are being replied to with PRIVMSG, which is causing message loops on our server in conjunction with services like NickServ. This is technically a violation of the RFC: https://tools.ietf.org/html/rfc1459#section-4.4.2

**Comment by qaisjp** [comment]
Ok I'll fix this. Is this for PMs to the bot?

**Comment by ja5087** [comment]
Yup, specifically, it seems that the bot is sending `Private messaging Discord users is not supported, but I support commands! Type 'help'.` though that seems to be commented out so maybe we're just running an older version. I still see a few codepaths where this could happen but if you don't think so feel free to close.

**Comment by qaisjp** [comment]
Thank you for investigating this! Should be resolved now
