### ISSUE TITLE
IRC socket stay connected after the discord user go offline

### ISSUE THREAD

**Issue by tchattons** [qaisjp/go-discord-irc#54]
Hello, IRC sockets stay connected after the discord user go offline

log:

DEBU[0017] PRESENCE offline                              id=6254184040182xxxxx
INFO[0017] ignoring a HandleUser                         err="Username or Discriminator is empty" user.Discriminator= user.ID=6254184040182xxxxx user.Username=

how to fix it please

Thank you in advance

**Comment by tchattons** [comment]
answered staff us in discord

**Comment by qaisjp** [comment]
answer from discord:

> It should disconnect after 24 hours
> There's a cool down

https://github.com/qaisjp/go-discord-irc/blob/95edad7da347da96ae5d30f0787f19771fce12d5/bridge/irc_manager.go#L17
