### ISSUE TITLE
Display JOIN, PART and KICK on discord

### ISSUE THREAD

**Issue by Rapman4** [qaisjp/go-discord-irc#55]
I would like to know if it is possible to display the join PART and Kick on discord?

**Comment by qaisjp** [comment]
- Does this feature exist right now? No.
- Possible? Yes.

**Comment by Rapman4** [comment]
My question can you add it?

**Comment by qaisjp** [comment]
this defaults to false https://github.com/qaisjp/go-discord-irc/commit/0dd8f8e90187f7aa78d5902b228e8ca5e9cb208b
