### ISSUE TITLE
Add IgnoreNick config directive to ignore certain IRC nicks (ascii art bots, url echos, etc)

### ISSUE THREAD

**Issue by yunginnanet** [qaisjp/go-discord-irc#63]
I went ahead and hardcoded our artbot as an ignore into my copy. It should be fairly simple to make this a config directive as it is in Matterbridge. I'll fork at some point if I have time

**Comment by llmII** [comment]
This should be resolved (in a far better manner) in #82. Allows for ignoring IRC hostmasks.
