### ISSUE TITLE
error="can't open irc connection: dial tcp [::1]:6697: connect: connection refused"

### ISSUE THREAD

**Issue by IoIxDButStronger** [qaisjp/go-discord-irc#66]
Currently running a server with InspIRCd that I have confirmed is running on the port 6697 and is accepting connections except for the one from go-discord-irc. I wish I could provide more info besides this [and the config file](https://pastebin.com/raw/rS4nfaus) but it seems `debug=true` does not provide extra info. If I need to check a log file for more info please tell me, but as is this is all I can offer. I should feel it's important to note I got a friend who actually uses go to compile this due to frustrations with the current process.

```
root@DietPi:/home/gavin/Discord# ./inspircd status
InspIRCd is running (PID: 23258)
root@DietPi:/home/gavin/Discord# ./go-discord-irc --config config.yml
INFO[0000] Loading configuration...                      ConfigName=config ConfigPath=. ConfigType=yml
INFO[0000] Cooldown duration for IRC puppets is 24h0m0s
FATA[0000] Go-Discord-IRC failed to start.               error="can't open irc connection: dial tcp [::1]:6697: connect: connection refused"
root@DietPi:/home/gavin/Discord#
```

**Comment by IoIxDButStronger** [comment]
Solved it.

The IP needed to be the raw IP as it was in the config file, but sublime text wasn't actually saving the file properly so it was still trying to connect to localhost.

**Comment by qaisjp** [comment]
thanks. is there anything i can do to help improve things or was this just a saving problem?

> I should feel it's important to note I got a friend who actually uses go to compile this due to frustrations with the current process.

what do you mean?
